/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/8.1/userguide/multi_project_builds.html
 */

rootProject.name = "gradle-testing-performance"

include("template")


include(
    "unit-only",
    "unit-only:module1",
    "unit-only:module2",
    "unit-only:module3",
    "unit-only:module4",
    "unit-only:module5",
    "unit-only:module6",
    "unit-only:module7",
    "unit-only:module8",
    "unit-only:module9",
    "unit-only:module10",
    "unit-only:module11",
    "unit-only:module12",
    "unit-only:module13",
    "unit-only:module14",
    "unit-only:module15",
    "unit-only:module16",
    "unit-only:module17",
    "unit-only:module18",
    "unit-only:module19",
    "unit-only:module20"
)